package com.observability.commerce;
import java.math.BigDecimal; import java.sql.*; import java.time.*; import java.util.*; import org.slf4j.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.dao.*; import org.springframework.http.*; import org.springframework.jdbc.core.*; import org.springframework.jdbc.support.GeneratedKeyHolder; import org.springframework.jdbc.support.KeyHolder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.client.*;
@Service public class CommerceService { private final JdbcTemplate db; private final RestTemplate http; @Value("${app.payment.url}") private String paymentUrl; @Value("${app.shipping.url}") private String shippingUrl; private static final Logger log=LoggerFactory.getLogger(CommerceService.class); public CommerceService(JdbcTemplate d,RestTemplate h){db=d;http=h;}
 public List<Map<String,Object>> products(String q,String category,int page,int size){String where=" WHERE p.active=true ";List<Object>a=new ArrayList<>();if(q!=null&&!q.isEmpty()){where+=" AND (lower(p.name) like ? OR lower(p.sku) like ? )";a.add("%"+q.toLowerCase()+"%");a.add("%"+q.toLowerCase()+"%");}if(category!=null&&!category.isEmpty()){where+=" AND c.name=?";a.add(category);}a.add(size);a.add(page*size);return db.queryForList("SELECT p.id,p.sku,p.name,p.description,p.price,c.name category,i.quantity inventory,i.reorder_level FROM products p JOIN categories c ON c.id=p.category_id JOIN inventory i ON i.product_id=p.id"+where+" ORDER BY p.name LIMIT ? OFFSET ?",a.toArray());}
 public Map<String,Object> product(long id){try{return db.queryForMap("SELECT p.id,p.sku,p.name,p.description,p.price,c.name category,i.quantity inventory,i.reorder_level FROM products p JOIN categories c ON c.id=p.category_id JOIN inventory i ON i.product_id=p.id WHERE p.id=?",id);}catch(EmptyResultDataAccessException e){throw new ApiException(HttpStatus.NOT_FOUND,"Product not found");}}
 public List<Map<String,Object>> customers(String q){return db.queryForList("SELECT id,customer_number,first_name,last_name,email,company,created_at FROM customers WHERE (?='' OR lower(first_name||' '||last_name||' '||email) LIKE ?) ORDER BY id LIMIT 100",q==null?"":q,"%"+(q==null?"":q.toLowerCase())+"%");}
 public List<Map<String,Object>> customerOrders(long id){return db.queryForList("SELECT id,order_number,status,total_amount,created_at FROM orders WHERE customer_id=? ORDER BY created_at DESC",id);}
 public Map<String,Object> dashboard(){Map<String,Object>x=new LinkedHashMap<>();x.put("customers",db.queryForObject("SELECT count(*) FROM customers",Long.class));x.put("orders",db.queryForObject("SELECT count(*) FROM orders",Long.class));x.put("revenue",db.queryForObject("SELECT coalesce(sum(total_amount),0) FROM orders WHERE status NOT IN ('PAYMENT_FAILED','CANCELLED')",BigDecimal.class));x.put("pendingOrders",db.queryForObject("SELECT count(*) FROM orders WHERE status IN ('ORDER_CREATED','PAYMENT_PENDING','PROCESSING')",Long.class));x.put("failedOrders",db.queryForObject("SELECT count(*) FROM orders WHERE status='PAYMENT_FAILED'",Long.class));x.put("lowStock",db.queryForObject("SELECT count(*) FROM inventory WHERE quantity<=reorder_level",Long.class));x.put("recentOrders",db.queryForList("SELECT o.id,o.order_number,o.status,o.total_amount,o.created_at,c.first_name||' '||c.last_name customer FROM orders o JOIN customers c ON c.id=o.customer_id ORDER BY o.created_at DESC LIMIT 8"));x.put("statusDistribution",db.queryForList("SELECT status,count(*) total FROM orders GROUP BY status ORDER BY total DESC"));return x;}
 public Map<String,Object> order(long id){try{return db.queryForMap("SELECT o.id,o.order_number,o.status,o.total_amount,o.discount_amount,o.created_at,c.first_name||' '||c.last_name customer FROM orders o JOIN customers c ON c.id=o.customer_id WHERE o.id=?",id);}catch(EmptyResultDataAccessException e){throw new ApiException(HttpStatus.NOT_FOUND,"Order not found");}}
 @Transactional public Map<String,Object> createOrder(Map<String,Object> body){Number cid=(Number)body.get("customerId");List<Map<String,Object>> items=(List<Map<String,Object>>)body.get("items");if(cid==null||items==null||items.isEmpty())throw new ApiException(HttpStatus.BAD_REQUEST,"customerId and at least one item are required");BigDecimal total=BigDecimal.ZERO;for(Map<String,Object>i:items){Number pid=(Number)i.get("productId"),qty=(Number)i.get("quantity");if(pid==null||qty==null||qty.intValue()<1)throw new ApiException(HttpStatus.UNPROCESSABLE_ENTITY,"Invalid order item");Map<String,Object>p=product(pid.longValue());if(((Number)p.get("inventory")).intValue()<qty.intValue())throw new ApiException(HttpStatus.CONFLICT,"Insufficient inventory for "+p.get("sku"));total=total.add((BigDecimal)p.get("price").multiply(BigDecimal.valueOf(qty.longValue())));}
 String code="ORD-"+UUID.randomUUID().toString().substring(0,8).toUpperCase();KeyHolder h=new GeneratedKeyHolder();db.update(c->{PreparedStatement s=c.prepareStatement("INSERT INTO orders(order_number,customer_id,status,total_amount,discount_amount) VALUES(?,?, 'ORDER_CREATED',?,0)",Statement.RETURN_GENERATED_KEYS);s.setString(1,code);s.setLong(2,cid.longValue());s.setBigDecimal(3,total);return s;},h);long oid=h.getKey().longValue();for(Map<String,Object>i:items){long pid=((Number)i.get("productId")).longValue();int q=((Number)i.get("quantity")).intValue();BigDecimal price=(BigDecimal)product(pid).get("price");db.update("INSERT INTO order_items(order_id,product_id,quantity,unit_price,line_total) VALUES(?,?,?,?,?)",oid,pid,q,price,price.multiply(BigDecimal.valueOf(q)));db.update("UPDATE inventory SET quantity=quantity-?,updated_at=now() WHERE product_id=?",q,pid);} Map<String,Object> request=new HashMap<>();request.put("orderId",oid);request.put("amount",total);Map<String,Object> payment=external(paymentUrl,request);db.update("INSERT INTO payments(order_id,status,amount,provider_reference) VALUES(?,?,?,?)",oid,"COMPLETED",total,String.valueOf(payment.get("reference")));Map<String,Object> shipping=external(shippingUrl,request);db.update("INSERT INTO shipments(order_id,status,tracking_number) VALUES(?,?,?)",oid,"PENDING",String.valueOf(shipping.get("reference")));db.update("UPDATE orders SET status='PROCESSING',updated_at=now() WHERE id=?",oid);db.update("INSERT INTO order_status_history(order_id,status,message) VALUES(?,?,?)",oid,"PROCESSING","Payment approved; shipment created");log.info("Order created orderId={} customerId={}",oid,cid);return order(oid);}
 public Map<String,Object> health(){Map<String,Object>x=new LinkedHashMap<>();x.put("status","UP");x.put("database",db.queryForObject("SELECT 1",Integer.class)==1?"UP":"DOWN");x.put("time",Instant.now().toString());return x;}
 public Map<String,Object> external(String url,Map<String,Object>b){try{return http.postForObject(url+"/process",b,Map.class);}catch(RestClientException e){throw new ApiException(HttpStatus.BAD_GATEWAY,"External service unavailable: "+e.getMessage());}}
}
